PROXY_PORT = 5558
SENSOR_PORT = 5001
CLOUD_PORT = 5001
ASPERSOR_PORT = 5001
PROXY_BACKUP_PORT=5001
SC_PROXY_PORT=5001
SC_EDGE_PORT=5001
SC_CLOUD_PORT=5001

IP_PROXY="192.168.193.79" 
IP_PROXY_BACKUP="" 
IP_CLOUD="" 
IP_SC_PROXY="" 
IP_SC_EDGE="" 
IP_SC_CLOUD="" 
IP_ASPERSOR="" 

CANT_SENSORES=2

SENSOR_HUMO="humo"
SENSOR_HUMEDAD="humedad"
SENSOR_TEMPERATURA="temperatura"

ARCHIVO_HUMO="files/humo.txt"
ARCHIVO_HUMEDAD="files/humedad.txt"
ARCHIVO_TEMPERATURA="files/temperatura.txt"

TIPO_RESULTADO_MUESTRA="Muestra"
TIPO_RESULTADO_ALERTA="Alerta"
TIPO_RESULTADO_ERROR="Error"

MAX_HUMO=True
MIN_HUMO=False
TIEMPO_HUMO=5

MAX_HUMEDAD=100
MIN_HUMEDAD=70
TIEMPO_HUMEDAD=5

MAX_TEMPERATURA=29.4
MIN_TEMPERATURA=11
TIEMPO_TEMPERATURA=6

