# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x06\x63lient\"1\n\rClientRequest\x12\x0f\n\x07\x63\x61teto1\x18\x01 \x01(\x02\x12\x0f\n\x07\x63\x61teto2\x18\x02 \x01(\x02\"!\n\x0b\x43lientReply\x12\x12\n\nhipotenusa\x18\x01 \x01(\x02\x32H\n\x06\x43lient\x12>\n\x10RequestOperation\x12\x15.client.ClientRequest\x1a\x13.client.ClientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTREQUEST']._serialized_start=24
  _globals['_CLIENTREQUEST']._serialized_end=73
  _globals['_CLIENTREPLY']._serialized_start=75
  _globals['_CLIENTREPLY']._serialized_end=108
  _globals['_CLIENT']._serialized_start=110
  _globals['_CLIENT']._serialized_end=182
# @@protoc_insertion_point(module_scope)
