# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import client_pb2 as client__pb2


class ClientStub(object):
    """servicio cliente"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestOperation = channel.unary_unary(
            "/client.Client/RequestOperation",
            request_serializer=client__pb2.ClientRequest.SerializeToString,
            response_deserializer=client__pb2.ClientReply.FromString,
        )


class ClientServicer(object):
    """servicio cliente"""

    def RequestOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ClientServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "RequestOperation": grpc.unary_unary_rpc_method_handler(
            servicer.RequestOperation,
            request_deserializer=client__pb2.ClientRequest.FromString,
            response_serializer=client__pb2.ClientReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "client.Client", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Client(object):
    """servicio cliente"""

    @staticmethod
    def RequestOperation(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/client.Client/RequestOperation",
            client__pb2.ClientRequest.SerializeToString,
            client__pb2.ClientReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
