# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: op1.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\top1.proto\x12\x03op1\"\x1d\n\nOp1Request\x12\x0f\n\x07\x63\x61teto1\x18\x01 \x01(\x02\"\x1b\n\x08Op1Reply\x12\x0f\n\x07\x63\x61teto1\x18\x01 \x01(\x02\x32\x33\n\x03Op1\x12,\n\nOperation1\x12\x0f.op1.Op1Request\x1a\r.op1.Op1Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OP1REQUEST']._serialized_start=18
  _globals['_OP1REQUEST']._serialized_end=47
  _globals['_OP1REPLY']._serialized_start=49
  _globals['_OP1REPLY']._serialized_end=76
  _globals['_OP1']._serialized_start=78
  _globals['_OP1']._serialized_end=129
# @@protoc_insertion_point(module_scope)
