# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import op1_pb2 as op1__pb2


class Op1Stub(object):
    """servicio op1"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Operation1 = channel.unary_unary(
            "/op1.Op1/Operation1",
            request_serializer=op1__pb2.Op1Request.SerializeToString,
            response_deserializer=op1__pb2.Op1Reply.FromString,
        )


class Op1Servicer(object):
    """servicio op1"""

    def Operation1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_Op1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Operation1": grpc.unary_unary_rpc_method_handler(
            servicer.Operation1,
            request_deserializer=op1__pb2.Op1Request.FromString,
            response_serializer=op1__pb2.Op1Reply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "op1.Op1", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Op1(object):
    """servicio op1"""

    @staticmethod
    def Operation1(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/op1.Op1/Operation1",
            op1__pb2.Op1Request.SerializeToString,
            op1__pb2.Op1Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
