# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import op2_pb2 as op2__pb2


class Op2Stub(object):
    """servicio op2
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Operation2 = channel.unary_unary(
                '/op1.Op2/Operation2',
                request_serializer=op2__pb2.Op2Request.SerializeToString,
                response_deserializer=op2__pb2.Op2Reply.FromString,
                )


class Op2Servicer(object):
    """servicio op2
    """

    def Operation2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Op2Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Operation2': grpc.unary_unary_rpc_method_handler(
                    servicer.Operation2,
                    request_deserializer=op2__pb2.Op2Request.FromString,
                    response_serializer=op2__pb2.Op2Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'op1.Op2', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Op2(object):
    """servicio op2
    """

    @staticmethod
    def Operation2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/op1.Op2/Operation2',
            op2__pb2.Op2Request.SerializeToString,
            op2__pb2.Op2Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
