# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: op3.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\top3.proto\x12\x03op3\".\n\nOp3Request\x12\x0f\n\x07\x63\x61teto1\x18\x01 \x01(\x02\x12\x0f\n\x07\x63\x61teto2\x18\x02 \x01(\x02\"\x1e\n\x08Op3Reply\x12\x12\n\nhipotenusa\x18\x01 \x01(\x02\x32\x33\n\x03Op3\x12,\n\nOperation3\x12\x0f.op3.Op3Request\x1a\r.op3.Op3Replyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op3_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OP3REQUEST']._serialized_start=18
  _globals['_OP3REQUEST']._serialized_end=64
  _globals['_OP3REPLY']._serialized_start=66
  _globals['_OP3REPLY']._serialized_end=96
  _globals['_OP3']._serialized_start=98
  _globals['_OP3']._serialized_end=149
# @@protoc_insertion_point(module_scope)
